
-- Projects seed
INSERT INTO public.projects (
  title, slug, client_display_name, client_type, industry, date_start, date_end,
  status, confidentiality, featured, short_focus, project_type, role,
  sm_themes, automation_themes, tags,
  context_html, challenge_html, my_role_html, approach_html, contributions_html, outcomes_html, lessons_html,
  meta_description, meta_keywords
) VALUES
(
  'Enterprise ITSM Operating Model Redesign',
  'enterprise-itsm-operating-model-redesign',
  'Global Financial Services Organisation',
  'enterprise', 'Financial Services',
  '2021-03-01', '2022-06-01',
  'published', 'sanitised', true,
  'Redesigned the ITSM operating model for a 40,000-seat financial services organisation, moving from a fragmented, geography-first model to a globally consistent, outcome-focused service delivery framework.',
  'transformation', 'Principal Advisor',
  ARRAY['operating model', 'service strategy', 'service catalogue', 'continual improvement'],
  ARRAY['workflow automation', 'AI-assisted triage'],
  ARRAY['ITSM', 'operating model', 'financial services', 'transformation', 'ServiceNow'],
  '<p>A leading global financial services organisation had grown its IT service management capability through acquisition over a decade. The result was 14 distinct regional operating models, 9 different ITSM toolsets, and no common language for service quality, capacity, or demand.</p>',
  '<p>The primary challenge was not technical — it was organisational. Each region had deep ownership of its practices and significant political resistance to standardisation perceived as centralisation. The business was simultaneously under pressure to reduce IT cost and improve employee experience scores that had fallen below industry benchmarks.</p>',
  '<p>I served as Principal Advisor for operating model design, working directly with the Global CIO and regional IT leaders. My role spanned discovery, framework design, stakeholder alignment, and implementation governance over 15 months.</p>',
  '<p>The approach centred on building a Universal Service Model — a common vocabulary, ownership structure, and performance framework that each region could adopt without surrendering local context. We used the USMBOK framework as the reference architecture and conducted structured workshops with 40+ IT leaders across 8 regions.</p>',
  '<ul><li>Designed the Global IT Service Architecture covering 120 services across 6 towers</li><li>Developed the Service Ownership model and RACI for all tier-1 and tier-2 services</li><li>Created the Enterprise Service Catalogue taxonomy adopted as the global standard</li><li>Led the vendor selection process for a consolidated ITSM platform</li><li>Delivered executive education programme for 60 IT leaders on service management maturity</li></ul>',
  '<ul><li>Reduced ITSM toolset count from 9 to 2 within 18 months of framework adoption</li><li>Employee technology experience score improved from 54 to 71 (NPS-equivalent) within 12 months</li><li>Incident resolution SLA compliance improved from 67% to 89% globally</li><li>Estimated £4.2M annual run-rate cost saving from operating model consolidation</li></ul>',
  '<p>The most durable lesson: operating model change in large organisations is fundamentally a change management challenge. The technical architecture is the easy part. Sustained investment in stakeholder engagement, local champion development, and executive sponsorship is the differentiator between transformation and shelf-ware.</p>',
  'Enterprise ITSM operating model redesign for a global financial services organisation — 40,000 seats, 14 regional models consolidated to a universal framework.',
  ARRAY['ITSM', 'operating model', 'service management', 'financial services', 'transformation']
),
(
  'Intelligent Automation Strategy for IT Operations',
  'intelligent-automation-strategy-it-operations',
  'Major Healthcare Network',
  'enterprise', 'Healthcare',
  '2020-09-01', '2021-08-01',
  'published', 'sanitised', true,
  'Developed and implemented an intelligent automation strategy for a 25-hospital healthcare network IT operations team, targeting tier-1 service desk volume reduction and infrastructure monitoring automation.',
  'advisory + implementation', 'Strategic Advisor & Programme Lead',
  ARRAY['service operations', 'continual improvement', 'knowledge management'],
  ARRAY['RPA', 'AI-assisted triage', 'workflow automation', 'conversational AI', 'monitoring automation'],
  ARRAY['intelligent automation', 'healthcare IT', 'service desk', 'RPA', 'AI', 'chatbot'],
  '<p>A 25-hospital network with a centralised IT operations team was managing 18,000 monthly service desk contacts, 62% of which were password resets, software access requests, and standard HR-triggered provisioning. The operations team was under-resourced and experiencing analyst burnout.</p>',
  '<p>Previous automation attempts had failed — two RPA pilots had been abandoned due to poor change resilience and insufficient business case rigour. There was organisational scepticism about automation and significant union concerns about job displacement. A credible strategy needed to address both the technical and human dimensions.</p>',
  '<p>I was engaged as Strategic Advisor with a mandate to diagnose, design, and oversee implementation of an automation programme that was sustainable, human-centred, and governed. I worked alongside the CIO, IT Operations Director, and an internal delivery team over 11 months.</p>',
  '<p>We began with a 6-week automation maturity assessment using a proprietary framework that evaluated process stability, data quality, change frequency, and human value. Only processes scoring above threshold were advanced to automation design. We paired every automation with an explicit "human role redefinition" plan — not elimination, but evolution.</p>',
  '<ul><li>Delivered automation maturity assessment across 340 service desk process variants</li><li>Designed and governed implementation of 18 automation candidates in priority sequence</li><li>Introduced conversational AI triage layer on service portal reducing mis-categorisation by 44%</li><li>Developed automation governance framework adopted as standard for future programmes</li><li>Ran 4 "automation literacy" workshops for 120 IT staff to address concerns and build capability</li></ul>',
  '<ul><li>Tier-1 contact volume reduced by 38% within 6 months of automation go-live</li><li>Average resolution time for in-scope requests dropped from 4.2 hours to 18 minutes</li><li>Zero redundancies — all 14 analysts in scope were redeployed to higher-value work</li><li>Programme ROI calculated at 280% over 3 years, validated by independent finance review</li></ul>',
  '<p>Human-centred automation is not a nice-to-have — it is a commercial imperative. Programmes that ignore the people impact fail not because the technology doesn''t work, but because adoption collapses under fear. Starting with transparency, involving analysts in automation design, and making the "what happens to me?" question explicit and answerable was the single most important decision of this programme.</p>',
  'Intelligent automation strategy for a 25-hospital healthcare IT operation — 38% tier-1 volume reduction with zero redundancies.',
  ARRAY['intelligent automation', 'healthcare IT', 'RPA', 'AI', 'service desk automation']
),
(
  'Service Management Framework for SaaS Platform Provider',
  'service-management-framework-saas-provider',
  'Enterprise SaaS Provider',
  'technology', 'Software / Technology',
  '2019-02-01', '2019-10-01',
  'published', 'public', true,
  'Designed and implemented a service management framework for a fast-scaling SaaS provider transitioning from startup operational practices to enterprise-grade service delivery.',
  'framework design + implementation', 'Framework Designer & Coach',
  ARRAY['service catalogue', 'incident management', 'service level management', 'continual improvement'],
  ARRAY['workflow automation', 'monitoring automation'],
  ARRAY['SaaS', 'service management', 'scaling', 'ITIL', 'startup to enterprise'],
  '<p>A SaaS provider that had grown from 50 to 500 employees in 3 years was experiencing the operational consequences of rapid scale — inconsistent incident response, no formal SLA structure, customer escalations handled ad hoc, and an engineering culture resistant to process formalisation.</p>',
  '<p>The challenge was cultural as much as operational. The founding team valued speed and autonomy. Any service management intervention perceived as bureaucratic would be rejected. The framework needed to be pragmatic, minimal, and demonstrably connected to business outcomes their engineers and executives already cared about.</p>',
  '<p>I was engaged as Framework Designer and Coach, responsible for assessment, framework design, tooling guidance, and a 6-month embedded coaching programme for the Head of Support and VP Engineering.</p>',
  '<p>We adopted a "minimum viable service management" philosophy — designing only what was needed to solve real problems visible to customers and engineers today. Starting with incident and problem management, we added service level management and a lightweight catalogue in sequence, each justified by a specific pain point rather than framework completeness.</p>',
  '<ul><li>Designed 7-process service management framework tailored to SaaS operational context</li><li>Implemented incident severity model and escalation playbook adopted company-wide within 60 days</li><li>Developed SLA/SLO structure for 3 customer tiers with internal OLA alignment</li><li>Coached Head of Support through first 3 major incident reviews using structured approach</li></ul>',
  '<ul><li>P1 incident mean time to restore (MTTR) reduced from 4.1 hours to 1.3 hours</li><li>Customer-reported dissatisfaction incidents reduced by 60% in 9 months post-implementation</li><li>Framework adopted as company standard; Head of Support promoted to VP Service Operations</li></ul>',
  '<p>Startups do not need less service management — they need service management that speaks their language. Connecting every practice to an outcome engineers or customers already care about ("faster recovery", "fewer 3am pages", "customers stop churning") is the translation layer that makes frameworks land in high-velocity organisations.</p>',
  'Service management framework design for a fast-scaling SaaS provider — practical, minimal, and connected to outcomes engineers care about.',
  ARRAY['service management', 'SaaS', 'ITIL', 'incident management', 'scaling']
),
(
  'AI-Augmented Knowledge Management Programme',
  'ai-augmented-knowledge-management',
  'Government Agency (Sanitised)',
  'government', 'Government / Public Sector',
  '2022-04-01', '2023-03-01',
  'published', 'sanitised', false,
  'Designed and oversaw the implementation of an AI-augmented knowledge management programme for a large government agency, integrating machine learning-assisted article recommendation into the service portal.',
  'advisory', 'Knowledge Strategy Advisor',
  ARRAY['knowledge management', 'self-service', 'continual improvement'],
  ARRAY['AI recommendation', 'ML classification', 'conversational AI'],
  ARRAY['knowledge management', 'AI', 'government IT', 'self-service', 'KCS'],
  '<p>A central government agency operating a 400-seat service desk was managing 22,000 monthly contacts, with self-service deflection rates stuck at 12% — well below the 35-45% benchmark for comparable organisations. The knowledge base contained 9,400 articles, many outdated or duplicated, with no governance process.</p>',
  '<p>The agency had invested heavily in a new service portal but adoption remained low. Analysis revealed that 73% of portal visitors who attempted self-service abandoned without resolution — a trust problem rooted in article quality and findability. Adding AI to poor-quality knowledge would amplify the problem rather than solve it.</p>',
  '<p>I served as Knowledge Strategy Advisor, responsible for the knowledge management foundation design and AI integration governance. I worked alongside the agency''s digital team and an AI vendor over 11 months.</p>',
  '<p>We sequenced the programme deliberately: knowledge quality remediation before AI augmentation. A KCS-aligned governance model was implemented first, reducing the active article count from 9,400 to 4,200 verified, current articles. Only then was AI recommendation layered in, trained on verified content and user resolution signals.</p>',
  '<ul><li>Designed KCS-aligned knowledge governance framework and article lifecycle process</li><li>Led knowledge audit reducing article count by 55% while improving coverage of top 200 contact types</li><li>Defined AI training data requirements and recommendation quality criteria for vendor engagement</li><li>Developed self-service experience design with UX team based on user research findings</li></ul>',
  '<ul><li>Self-service deflection rate increased from 12% to 41% within 9 months of AI recommendation go-live</li><li>Article confidence scores (user ratings) improved from 2.1 to 4.3 out of 5</li><li>Estimated 180,000 contacts/year deflected, releasing analyst capacity for complex work</li></ul>',
  '<p>AI in knowledge management is a multiplier — it multiplies what is already there. If the underlying knowledge is poor, AI makes poor knowledge more visible and more confidently wrong. The investment in knowledge quality was not a prerequisite to be rushed through; it was the programme.</p>',
  'AI-augmented knowledge management for a government agency — self-service deflection increased from 12% to 41%.',
  ARRAY['knowledge management', 'AI', 'KCS', 'self-service', 'government IT']
);
