
-- Insert Service Management 101 employer
INSERT INTO employers (name, short_name, sort_order)
VALUES ('Service Management 101', 'SM101', 10)
ON CONFLICT DO NOTHING;

-- Seed projects linked to Service Management 101
-- Uses a CTE to look up the employer id cleanly
WITH emp AS (
  SELECT id FROM employers WHERE name = 'Service Management 101' LIMIT 1
)
INSERT INTO projects (
  title, slug, client_display_name, client_name, show_client_name,
  employer_id, industry, project_type, role,
  short_focus, status, confidentiality,
  sm_themes, tags,
  date_start, date_end
)
SELECT
  p.title, p.slug, p.client, p.client, true,
  emp.id, p.industry, p.project_type, p.role,
  p.short_focus, 'published', 'public',
  p.sm_themes, p.tags,
  p.date_start, p.date_end
FROM emp, (VALUES

  ('Accenture – ITIL Education',
   'accenture-itil-education', 'Accenture', 'Professional Services',
   'advisory', 'Principal Consultant / Trainer',
   'Delivered ITIL education programme for Accenture consultants.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Education', 'Consulting'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Affiliated Computer Services – Strategy Development',
   'affiliated-computer-services-strategy', 'Affiliated Computer Services', 'IT Services',
   'advisory', 'Senior Consultant',
   'Strategy development engagement covering ITSM framework alignment.',
   ARRAY['Strategy Development'], ARRAY['ITSM', 'Strategy'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Air Products and Chemicals – ITIL Education & Strategy',
   'air-products-chemicals-itil', 'Air Products and Chemicals', 'Manufacturing / Chemicals',
   'implementation', 'Principal Consultant / Trainer',
   'ITIL education, strategy enablement, and project support for a global chemicals manufacturer.',
   ARRAY['ITIL Education', 'Strategy Development', 'Project Support'], ARRAY['ITIL', 'Education', 'Strategy'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Allstate Insurance – ITIL Education & Strategy',
   'allstate-insurance-itil', 'Allstate Insurance', 'Insurance',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for a major US insurance provider.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Education', 'Insurance'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('American Express – ITIL Education & Strategy',
   'american-express-itil', 'American Express', 'Financial Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for the global financial services firm.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Financial Services'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Advanced Technology Services – ITIL Education & Strategy',
   'advanced-technology-services-itil', 'Advanced Technology Services', 'IT Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for a managed services provider.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Managed Services'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Bank One – ITSM Enablement & Education',
   'bank-one-itsm', 'Bank One', 'Financial Services',
   'implementation', 'Principal Consultant / Trainer',
   'ITSM enablement, project support and education for a major US banking institution.',
   ARRAY['ITSM Education', 'Project Support'], ARRAY['ITSM', 'Banking', 'Enablement'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Beeline Russia – ITSM Education & Strategy',
   'beeline-russia-itsm', 'Beeline (Russia Telecom)', 'Telecommunications',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for one of Russia''s largest telecom operators.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Telecoms', 'Russia'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Blue Cross Blue Shield of Florida – ITIL Education & Strategy',
   'bcbs-florida-itil', 'Blue Cross Blue Shield of Florida', 'Healthcare / Insurance',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for a major US health insurer.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Healthcare', 'Insurance'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('BMC Software – ITIL Education',
   'bmc-software-itil', 'BMC Software', 'Software / Technology',
   'advisory', 'Principal Consultant / Trainer',
   'Delivered ITIL education programme for BMC Software staff and partners.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Education', 'Software'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Cap Gemini – Data Center Assessment & Strategy',
   'cap-gemini-data-center', 'Cap Gemini', 'IT Services / Consulting',
   'advisory', 'Senior Consultant',
   'Data centre assessment and strategy reset for Cap Gemini North America operations.',
   ARRAY['Strategy Development', 'Assessment'], ARRAY['Data Centre', 'Strategy', 'Assessment'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Caribbean Development Bank – ITIL Education & Strategy',
   'caribbean-development-bank-itil', 'Caribbean Development Bank', 'Financial Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for the regional development finance institution.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Banking', 'Caribbean'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Caterpillar – ITSM Enablement & Strategic Planning',
   'caterpillar-itsm', 'Caterpillar', 'Manufacturing',
   'implementation', 'Principal Consultant',
   'ITSM enablement, strategic planning, project support and education for the global heavy machinery leader.',
   ARRAY['ITSM Education', 'Strategy Development', 'Project Support'], ARRAY['ITSM', 'Manufacturing', 'Enablement'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('City of Carlsbad – ITIL Education & Strategy',
   'city-of-carlsbad-itil', 'City of Carlsbad', 'Government',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for the City of Carlsbad IT department.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Government', 'Local Authority'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('City of Fontana – ITIL Education & Project Support',
   'city-of-fontana-itil', 'City of Fontana', 'Government',
   'implementation', 'Principal Consultant / Trainer',
   'ITIL education and project support for the City of Fontana IT division.',
   ARRAY['ITIL Education', 'Project Support'], ARRAY['ITIL', 'Government'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('City of Oklahoma – Executive ITSM Education',
   'city-of-oklahoma-itsm', 'City of Oklahoma', 'Government',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education delivered to the executive leadership team of the City of Oklahoma.',
   ARRAY['ITSM Education'], ARRAY['ITSM', 'Government', 'Executive Education'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('CNF Service Company – ITIL Education & Strategy',
   'cnf-service-company-itil', 'CNF Service Company', 'Logistics',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for CNF Service Company.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Logistics'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Department of Homeland Security – ITIL & ITSM Education',
   'department-of-homeland-security-itil', 'Department of Homeland Security', 'Government / Federal',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL and ITSM education programme delivered to DHS technology teams.',
   ARRAY['ITIL Education', 'ITSM Education'], ARRAY['ITIL', 'ITSM', 'Federal Government'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Dickson Allan – ITSM Education & Strategy',
   'dickson-allan-itsm', 'Dickson Allan', 'Professional Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development engagement.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Strategy'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Dow Jones – Project Support & ITIL Education',
   'dow-jones-itil', 'Dow Jones', 'Media / Publishing',
   'implementation', 'Principal Consultant / Trainer',
   'ITIL education and project support for Dow Jones technology operations.',
   ARRAY['ITIL Education', 'Project Support'], ARRAY['ITIL', 'Media'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Duke University – ITIL Education & Strategy',
   'duke-university-itil', 'Duke University', 'Higher Education',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for Duke University IT services.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Higher Education'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('EMC Software – ITIL Education',
   'emc-software-itil', 'EMC Software', 'Software / Technology',
   'advisory', 'Principal Consultant / Trainer',
   'Delivered ITIL education for EMC Software staff.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Education', 'Software'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Emerson – ITIL Education',
   'emerson-itil', 'Emerson', 'Manufacturing / Technology',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme delivered to Emerson technology teams.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Manufacturing'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Ernst and Young – ITSM Education',
   'ernst-young-itsm', 'Ernst and Young', 'Professional Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education delivered to Ernst and Young consulting and technology staff.',
   ARRAY['ITSM Education'], ARRAY['ITSM', 'Professional Services'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Evertec Puerto Rico – ITIL Education & Strategy',
   'evertec-puerto-rico-itil', 'Evertec Puerto Rico', 'Financial Technology',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for the Caribbean payment technology provider.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'FinTech', 'Caribbean'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Farmland USA – Data Center & Service Management Strategy',
   'farmland-usa-data-center', 'Farmland USA', 'Agriculture / Food',
   'implementation', 'Principal Consultant',
   'Data centre standup and service management strategy development for Farmland USA.',
   ARRAY['Strategy Development'], ARRAY['Data Centre', 'Strategy', 'Agriculture'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Gemological Institute of America – ITIL Education & Strategy',
   'gia-itil', 'Gemological Institute of America', 'Education / Non-Profit',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for the GIA technology team.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Education'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('General Dynamics – ITIL Education & Strategy',
   'general-dynamics-itil', 'General Dynamics', 'Defence / Aerospace',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for General Dynamics IT operations.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Defence', 'Aerospace'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('General Motors – ITSM Strategic Planning',
   'general-motors-itsm', 'General Motors', 'Automotive',
   'advisory', 'Principal Consultant',
   'ITSM strategic planning and outsourcing project support for General Motors global IT.',
   ARRAY['Strategy Development', 'Project Support'], ARRAY['ITSM', 'Strategy', 'Automotive', 'Outsourcing'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Holy Cross Health Systems – ITSM Education & Data Center Transformation',
   'holy-cross-health-itsm', 'Holy Cross Health Systems', 'Healthcare',
   'implementation', 'Principal Consultant',
   'ITSM education, strategy development and data centre transformation for Holy Cross Health Systems.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Healthcare', 'Data Centre'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('IBM Tivoli – ITSM Education & Keynote',
   'ibm-tivoli-itsm', 'IBM Tivoli', 'Software / Technology',
   'advisory', 'Keynote Speaker / Trainer',
   'ITSM education and keynote delivery for IBM Tivoli events and partner programmes.',
   ARRAY['ITSM Education'], ARRAY['ITSM', 'IBM', 'Keynote'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Intel – ITSM Education & Strategy',
   'intel-itsm', 'Intel', 'Semiconductor / Technology',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for Intel IT operations.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Technology', 'Semiconductor'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Internal Revenue Service – ITIL Education',
   'irs-itil', 'Internal Revenue Service', 'Government / Federal',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme delivered to IRS technology and operations teams.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Federal Government'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Intuit – ITSM Education & Strategy',
   'intuit-itsm', 'Intuit', 'Software / FinTech',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for Intuit technology operations.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Software', 'FinTech'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Jockey Club – ITSM Education & Project Support',
   'jockey-club-itsm', 'Jockey Club', 'Sports / Gaming',
   'implementation', 'Principal Consultant / Trainer',
   'ITSM education and project support for Jockey Club IT operations.',
   ARRAY['ITSM Education', 'Project Support'], ARRAY['ITSM', 'Gaming'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Mayo Clinic – ITIL Education',
   'mayo-clinic-itil', 'Mayo Clinic', 'Healthcare',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme for Mayo Clinic IT staff.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Healthcare'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('McKee Foods – ITIL Education & Strategy',
   'mckee-foods-itil', 'McKee Foods', 'Food & Beverage',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for McKee Foods IT team.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Food & Beverage'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Meijer Foods – ITSM Enablement & Project Support',
   'meijer-foods-itsm', 'Meijer Foods', 'Retail / Food',
   'implementation', 'Principal Consultant',
   'ITSM enablement and project support for Meijer Foods IT operations.',
   ARRAY['ITSM Education', 'Project Support'], ARRAY['ITSM', 'Retail'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Merrill Lynch – Executive ITSM Education',
   'merrill-lynch-itsm', 'Merrill Lynch', 'Financial Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education delivered to the worldwide executive management team at Merrill Lynch.',
   ARRAY['ITSM Education'], ARRAY['ITSM', 'Financial Services', 'Executive Education'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Metamor – ITSM Education & Multi-Supplier Strategy',
   'metamor-itsm', 'Metamor', 'IT Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for a multi-supplier ecosystem at Metamor.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Multi-Supplier', 'Strategy'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Microsoft – ITIL Education & MOF Strategy',
   'microsoft-itil-mof', 'Microsoft', 'Software / Technology',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and Microsoft Operations Framework (MOF) strategy development.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'MOF', 'Microsoft'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Parkview Health Systems – ITSM Education & Strategy',
   'parkview-health-itsm', 'Parkview Health Systems', 'Healthcare',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for Parkview Health Systems.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Healthcare'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Pennsylvania Power and Light – ITIL Education & Strategy',
   'ppl-itil', 'Pennsylvania Power and Light', 'Energy / Utilities',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for PP&L technology operations.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Energy', 'Utilities'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Perot Systems – ITIL Education (Professional Services)',
   'perot-systems-itil', 'Perot Systems', 'IT Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education of core professional services team members at Perot Systems.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Managed Services'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('PricewaterhouseCoopers – ITIL Education & Strategy',
   'pwc-itil', 'PricewaterhouseCoopers', 'Professional Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for PwC technology and consulting teams.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Professional Services'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Quest Diagnostics – ITIL Education',
   'quest-diagnostics-itil', 'Quest Diagnostics', 'Healthcare / Diagnostics',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme for Quest Diagnostics IT staff.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Healthcare'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Quintiles – ITIL Education & Strategy',
   'quintiles-itil', 'Quintiles', 'Pharmaceutical / Life Sciences',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for Quintiles IT operations.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Pharma', 'Life Sciences'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Qwest – ITIL Education & Strategy',
   'qwest-itil', 'Qwest', 'Telecommunications',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for Qwest Communications.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Telecoms'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Raytheon Aircraft – ITSM Education & Strategy',
   'raytheon-aircraft-itsm', 'Raytheon Aircraft Corporation', 'Defence / Aerospace',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for Raytheon Aircraft IT operations.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Defence', 'Aerospace'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Robert Half Technologies – ITSM Education',
   'robert-half-itsm', 'Robert Half Technologies', 'Staffing / Professional Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education programme for Robert Half Technologies staff.',
   ARRAY['ITSM Education'], ARRAY['ITSM', 'Staffing'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('SAP America – ITSM Education',
   'sap-america-itsm', 'SAP America', 'Software / Technology',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education delivered to SAP America technology and consulting teams.',
   ARRAY['ITSM Education'], ARRAY['ITSM', 'SAP', 'Software'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Saudi Aramco – ITIL Education',
   'saudi-aramco-itil', 'Saudi Aramco', 'Energy / Oil & Gas',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme delivered to Saudi Aramco IT operations teams.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Oil & Gas', 'Energy'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('SC Johnson – ITSM Education & Strategy',
   'sc-johnson-itsm', 'SC Johnson', 'Consumer Goods',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for SC Johnson IT.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITSM', 'Consumer Goods'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Simplot – ITIL Education & Strategy',
   'simplot-itil', 'Simplot', 'Agriculture / Food',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for Simplot IT operations.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Agriculture'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Sitelite – ITSM Education & Strategy',
   'sitelite-itsm', 'Sitelite', 'IT Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development engagement.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Strategy'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Solar Turbines – ITSM Education & Strategy',
   'solar-turbines-itsm', 'Solar Turbines (Caterpillar)', 'Manufacturing / Energy',
   'advisory', 'Principal Consultant / Trainer',
   'Education and strategy development for Solar Turbines, a Caterpillar subsidiary.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Manufacturing', 'Energy'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('SPAWARS – ITIL Education',
   'spawars-itil', 'SPAWARS', 'Government / Defence',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education delivered to Space and Naval Warfare Systems Command IT teams.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Defence', 'Government'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Spectrum Health – ITSM Education & Strategy',
   'spectrum-health-itsm', 'Spectrum Health', 'Healthcare',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for Spectrum Health IT operations.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Healthcare'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Thomson Financial – ITIL Education & Strategy',
   'thomson-financial-itil', 'Thomson Financial', 'Financial Services / Media',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for Thomson Financial technology teams.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Financial Services'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('UC Davis Health Systems – ITIL Education & Strategy',
   'uc-davis-health-itil', 'UC Davis Health Systems', 'Healthcare / Education',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for UC Davis Health Systems IT.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Healthcare', 'Higher Education'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('UMB Bank – ITIL Education',
   'umb-bank-itil', 'UMB Bank', 'Financial Services',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme for UMB Bank IT staff.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Banking'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Union Carbide – ITSM Education & Configuration Architecture',
   'union-carbide-itsm', 'Union Carbide', 'Chemical / Manufacturing',
   'implementation', 'Principal Consultant',
   'ITSM education and configuration system architecture for Union Carbide.',
   ARRAY['ITSM Education', 'Configuration Management'], ARRAY['ITSM', 'Configuration Management', 'Manufacturing'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Union Dominion Realty Trust – ITSM Education & Strategy',
   'union-dominion-realty-itsm', 'Union Dominion Realty Trust', 'Real Estate',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for Union Dominion Realty Trust IT.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Real Estate'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Upsher Smith – ITIL Education',
   'upsher-smith-itil', 'Upsher Smith', 'Pharmaceutical',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme for Upsher-Smith Laboratories IT team.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Pharma'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('US Army – ITIL Education',
   'us-army-itil', 'US Army', 'Government / Defence',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme delivered to US Army technology and IT operations teams.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Defence', 'Government'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('US Navy – ITIL, Lean Education & Strategy',
   'us-navy-itil-lean', 'US Navy', 'Government / Defence',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL and Lean education combined with strategy development for US Navy IT teams.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Lean', 'Defence', 'Government'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('US Freightways – ITSM Education & Strategy',
   'us-freightways-itsm', 'US Freightways', 'Logistics / Transport',
   'advisory', 'Principal Consultant / Trainer',
   'ITSM education and strategy development for US Freightways IT operations.',
   ARRAY['ITSM Education', 'Strategy Development'], ARRAY['ITSM', 'Logistics', 'Transport'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('Verizon Business Services – ITIL Education & Strategy',
   'verizon-business-itil', 'Verizon Business Services', 'Telecommunications',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education and strategy development for Verizon Business Services IT teams.',
   ARRAY['ITIL Education', 'Strategy Development'], ARRAY['ITIL', 'Telecoms'],
   '2000-01-01'::date, '2005-12-31'::date),

  ('WiPro – ITIL Education',
   'wipro-itil', 'WiPro', 'IT Services / Outsourcing',
   'advisory', 'Principal Consultant / Trainer',
   'ITIL education programme delivered to WiPro consulting and delivery teams.',
   ARRAY['ITIL Education'], ARRAY['ITIL', 'Outsourcing', 'IT Services'],
   '2000-01-01'::date, '2005-12-31'::date)

) AS p(title, slug, client, industry, project_type, role, short_focus, sm_themes, tags, date_start, date_end)
ON CONFLICT (slug) DO NOTHING;
