INSERT INTO projects (
  title, slug, client_display_name, industry, project_type, status, confidentiality, featured,
  short_focus, role, date_start, date_end,
  sm_themes, automation_themes, tags,
  context_html, challenge_html, my_role_html, approach_html, outcomes_html, lessons_html
) VALUES
(
  'Global Industrial Manufacturer — Federated ITSM Merger & Integration',
  'global-manufacturer-federated-itsm-merger',
  'Global Industrial Manufacturer (Sanitised)',
  'Manufacturing / Transportation',
  'transformation',
  'published', 'sanitised', true,
  'Merging two radically different ServiceNow implementations into a single worldwide platform following a major corporate acquisition.',
  'BPC, OCM Lead, Trainer',
  '2019-09-01', '2020-02-28',
  ARRAY['Change Management','Service Portal','Knowledge Management','CMDB'],
  ARRAY['SolarWinds Integration','SCCM'],
  ARRAY['federated-change-management','merger','acquisition','catalog-reconciliation'],
  '<p>Following a major acquisition, two organisations with completely different ServiceNow implementations needed to become one worldwide ITSM operation. 270 catalog items and their associated workflows needed to be reconciled, change advisory board structures from both organisations needed to be federated, and knowledge article libraries merged without breaking existing user habits.</p>',
  '<p>The most complex element was the federated change management model — both organisations had legitimate governance requirements that could not simply be overridden by the acquiring company. Catalog reconciliation across 270 items required decisions on every item: retire, merge, or maintain separately.</p>',
  '<p>BPC and OCM Lead responsible for the overall blueprint design, federated change management operating model, catalog reconciliation strategy, and go-live coordination. Also delivered training for the combined service desk and change management teams.</p>',
  '<p>Developed a federated change management model that gave each organisation its own change board while routing changes through a shared approval workflow based on scope and risk. A decision matrix was applied to all 270 catalog items. A phased go-live approach prioritised the highest-volume services first.</p>',
  '<p>Successful go-live with no critical issues. The PM and Project Sponsor were vocal in their praise. Two minor issues were resolved before Monday morning business start. The federated change model has since been adopted as the standard for the combined organisation.</p>',
  '<p>Acquisition integrations require political sensitivity as well as technical skill. The federated governance model was the key insight — neither organisation would accept being subordinated to the other, but both could accept shared routing logic. Catalog reconciliation at scale requires a systematic decision framework, not case-by-case negotiation.</p>'
),
(
  'Major Urban Health System — Virtual Agent with NLU',
  'urban-health-system-virtual-agent-nlu',
  'Major Urban Health System (Sanitised)',
  'Healthcare',
  'implementation',
  'published', 'sanitised', true,
  'Design and deployment of an NLU-powered Virtual Agent handling clinical IT support conversations — check incident status, radiology PACS issues, medication scanner problems, and remote access requests.',
  'BPC Support, UX Lead',
  '2021-01-01', '2021-06-30',
  ARRAY['Virtual Agent','Knowledge Management','Incident Management'],
  ARRAY['NLU','Conversational AI'],
  ARRAY['virtual-agent','NLU','healthcare','conversational-design','AI'],
  '<p>A major urban health system needed to reduce call volume to its IT service desk while maintaining the responsiveness that clinical staff required. The environment was clinically sensitive — the system needed to handle highly specific healthcare IT request types that standard virtual agent templates did not address.</p>',
  '<p>Healthcare IT conversations are uniquely specific and high-stakes. Generic virtual agent deployments fail in clinical environments because they cannot handle the clinical vocabulary or the urgency sensitivity required. Designing conversational flows that correctly triaged clinical urgency required deep understanding of both conversational design principles and clinical workflows.</p>',
  '<p>Led UX and conversational design for the virtual agent. Responsible for conversation script development, intent design, and the triage logic that determined when to escalate to a live agent. Worked closely with clinical informatics and the IT service desk to validate conversation accuracy.</p>',
  '<p>Developed a custom conversation suitability assessment framework. Built eight initial conversation flows covering the highest-volume clinical IT topics. Applied NLU training using real ticket data from the service desk to improve intent recognition accuracy.</p>',
  '<p>The virtual agent launched successfully. The client was so pleased that a change order was immediately initiated to fast-track a second release. Hospital executives were already compiling a wish list of additional conversations before the first release completed its first week.</p>',
  '<p>Healthcare virtual agent deployments succeed when clinical subject matter experts are deeply involved in conversation design from the start. The conversation suitability framework proved essential for setting realistic scope expectations and ensuring the virtual agent handled only conversations where automation added genuine value.</p>'
),
(
  'Canadian Federal Research Organisation — Multi-Phase ITSM Transformation',
  'canadian-federal-research-itsm-transformation',
  'Canadian Federal Research Organisation (Sanitised)',
  'Government / Public Sector',
  'transformation',
  'published', 'sanitised', false,
  'Rapid 30-day ITSM re-implementation followed by an operational readiness programme and phased capability expansion including Major Incident Management and CSDM.',
  'BPC/Trainer, CSDM Lead',
  '2021-02-01', '2022-03-31',
  ARRAY['Incident Management','Problem Management','Change Management','Knowledge Management','Major Incident Management','CSDM'],
  ARRAY['SCCM Discovery'],
  ARRAY['government','CSDM','multi-phase','operational-readiness'],
  '<p>A Canadian federal research organisation required a rapid and complete re-implementation of its ServiceNow ITSM platform, establishing a clean operational baseline before expanding capabilities through subsequent phases. The organisation operated under specific regulatory and security constraints that required creative workshop and delivery approaches.</p>',
  '<p>Phase 1 was a 30-day sprint to deliver a working, documented ITSM baseline. Subsequent phases required building organisational capability — not just system configuration — through embedded coaching and a formal Operational Readiness Programme. Phase 1.2 introduced Major Incident Management and began the CSDM-aligned service portfolio.</p>',
  '<p>Delivered the initial re-implementation as lead BPC and trainer. Led the 30-day Operational Readiness Programme as embedded advisor and coach for incident, problem, change, and knowledge teams. Served as CSDM Lead for Phase 1.2.</p>',
  '<p>Phase 1 used a streamlined, pattern-based approach to meet the 30-day timeline. The Operational Readiness Programme embedded capability transfer through daily ride-along sessions. Phase 1.2 used CSDM as the structural framework for service portfolio design before any technical configuration began.</p>',
  '<p>Phase 1 delivered a clean, documented ITSM baseline within 30 days. The Operational Readiness Programme successfully transitioned operational responsibility to the internal team. Phase 1.2 established a service portfolio foundation that became the reference model for the organisation''s ongoing digital transformation.</p>',
  '<p>Multi-phase engagements build compounding value when each phase is designed with the next in mind. Operational readiness through embedded coaching consistently delivers better long-term adoption than formal training alone.</p>'
),
(
  'Global Alternative Investment Firm — Custom Security & Compliance Application Suite',
  'global-hedge-fund-custom-security-compliance-apps',
  'Global Alternative Investment Firm (Sanitised)',
  'Financial Services',
  'implementation',
  'published', 'sanitised', true,
  'Design and development of eleven custom applications plus a Workday integration to replace a legacy Archer/RSA platform — 30 custom tables, 2,000 dictionary entries, 8,500 configuration elements.',
  'BPC, UX, Dashboard & Report Design',
  '2021-07-01', '2022-01-31',
  ARRAY['Custom Application Development','CMDB'],
  ARRAY['Workday Integration','Legacy Data Migration'],
  ARRAY['custom-apps','archer-replacement','financial-services','security-compliance','high-complexity'],
  '<p>A global alternative investment firm had outgrown its Archer/RSA security and compliance platform. The migration to ServiceNow required not just a technical port but a complete redesign of 11 distinct application areas, including one capability that had never previously existed in Archer.</p>',
  '<p>The scope was extraordinary: 30 custom tables, 2,000 dictionary entries, and 8,500 individual configuration elements, plus a Workday integration and transform maps for legacy data import. One of the eleven applications had no precedent in the existing system and required pure greenfield design.</p>',
  '<p>Served as lead BPC and UX designer, responsible for overall application architecture, data model design, user experience across all eleven applications, dashboard and reporting design, and ACL strategy.</p>',
  '<p>Applied a structured decomposition approach to build a coherent data architecture before any individual application design began. The Workday integration was prioritised as a foundational data source. Legacy data migration used transform maps developed alongside the application design.</p>',
  '<p>The Bridgewater team described the quality as "stunning — it just works." Delivered on time and within agreed scope despite extraordinary complexity. The custom application suite became the firm''s primary security and compliance platform.</p>',
  '<p>Projects of extreme complexity require architectural discipline above all. Getting the data model right before building any individual application was the decision that made the project successful. The greenfield application was actually the easiest to design well, because it had no legacy assumptions to carry forward.</p>'
),
(
  'Major US Children''s Hospital — Full ITSM & ITOM Implementation',
  'major-childrens-hospital-itsm-itom',
  'Major US Children''s Hospital (Sanitised)',
  'Healthcare',
  'implementation',
  'published', 'sanitised', false,
  'Full ITSM and ITOM implementation including On-Call management, Outage Ticketing, CMDB, Service Portal, and mobile app, with integrations to clinical messaging and identity platforms.',
  'Supporting BPC, Training Design, On-Call & Dashboard Design',
  '2018-06-01', '2019-01-31',
  ARRAY['Incident Management','Problem Management','Change Management','CMDB','Knowledge Management','Service Portal','Service Catalog'],
  ARRAY['Rhapsody Integration','SailPoint Integration','eBonding'],
  ARRAY['healthcare','ITSM','ITOM','mobile','on-call-management','dashboard'],
  '<p>A major US children''s hospital required a comprehensive ITSM and ITOM implementation. The clinical environment added complexity — On-Call management, Outage Ticketing, and New Call processes needed to be designed with clinical sensitivity, and the mobile application component needed to function reliably in a hospital environment.</p>',
  '<p>Healthcare ITSM implementations require process designs that reflect clinical operational realities. The On-Call management component was particularly sensitive — workflows needed to match actual clinical escalation procedures precisely. Integrations with Rhapsody, SailPoint, and an eBonding connection added significant technical complexity.</p>',
  '<p>Supported the lead BPC on ITSM design and provided specialist support for training material development, On-Call process design, and dashboard design. Responsible for ensuring the training programme reflected the clinical context of the deployment.</p>',
  '<p>On-Call management and Outage Ticket design were treated as distinct workstreams with dedicated clinical operations stakeholder workshops. Dashboard design followed a leadership-first approach — understanding what hospital leadership needed to see before designing the underlying data structures.</p>',
  '<p>The go-live was described by the customer PM as going "much better than I even anticipated." On-Call and Outage management capabilities were operational from day one. The mobile application deployed successfully to clinical staff.</p>',
  '<p>Healthcare implementations succeed when clinical operations representatives are treated as equal partners in process design. On-Call management in particular requires validation against actual escalation scenarios — designed workflows that look correct on paper frequently fail the first clinical walkthrough.</p>'
),
(
  'Large Federal Credit Union — ITBM Suite & Virtual Agent NLU Programme',
  'large-federal-credit-union-itbm-virtual-agent',
  'Large Federal Credit Union (Sanitised)',
  'Financial Services',
  'implementation',
  'published', 'sanitised', true,
  'Full ITBM application suite for ISD — PPM, Demand, Resource Management, Labor Capitalization, and four major integrations — followed by a Virtual Agent NLU programme to build lasting internal conversational design capability.',
  'BPC, Conversational Design SME, UX',
  '2020-08-01', '2021-09-30',
  ARRAY['IT Business Management','Project Portfolio Management','Demand Management','Resource Management','Virtual Agent'],
  ARRAY['DRM Integration','Hyperion Integration','Apptio Integration','Fieldglass Integration','NLU'],
  ARRAY['ITBM','PPM','virtual-agent','NLU','credit-union','labor-capitalization'],
  '<p>A large federal credit union sought to consolidate PPM reporting, demand management, and resource planning into ServiceNow — enabling divestment of a separate data mart. A subsequent Virtual Agent phase focused on building internal NLU and conversational design capability rather than simply delivering a configured product.</p>',
  '<p>The ITBM programme required four major integrations alongside the full application suite, plus custom reports and a significant data migration. The Virtual Agent phase had a distinctive goal: "teach the team to fish" — building lasting internal capability rather than a dependency on external consultants.</p>',
  '<p>Led as BPC for the full ITBM suite, responsible for application design, integration strategy, and custom reporting. Served as Conversational Design SME and UX lead for the Virtual Agent phase, developing conversation scripts, a suitability framework, and translation policies for the internal team.</p>',
  '<p>The ITBM programme used a reporting-first design approach. The Virtual Agent programme began with Conversational Design 101 training for the internal team, followed by collaborative script development and a structured review process.</p>',
  '<p>The ITBM implementation was described as "pivotal in the credit union''s vision for digitally transforming the IT Operating Model." The Virtual Agent launched with no issues. The conversational design framework developed was recommended to other teams in the organisation.</p>',
  '<p>The most durable implementations build internal capability alongside technical delivery. The "teach to fish" goal changed how the team approached every design decision — they were learning, not just approving. That mindset shift produced a team that could independently extend the platform after the engagement closed.</p>'
),
(
  'Global Security Company — ITSM Platform Replacement (Legacy Remedy)',
  'global-security-company-itsm-remedy-replacement',
  'Global Security Services Company (Sanitised)',
  'Security Services',
  'transformation',
  'published', 'sanitised', false,
  'Replace a 20-year-old Remedy ITSM solution including all in-house custom enhancements, delivered to a non-negotiable hard deadline.',
  'Senior BPC',
  '2022-04-01', '2022-11-30',
  ARRAY['Incident Management','Problem Management','Change Management','Service Catalog','Knowledge Management','Service Portal'],
  ARRAY[]::text[],
  ARRAY['remedy-replacement','legacy-migration','deadline-driven'],
  '<p>A global security services company was running a 20-year-old BMC Remedy ITSM implementation that had accumulated two decades of in-house customisation. The platform was at end of life, and the organisation had set a hard deadline for replacement. The risk of a straightforward lift-and-shift was high — two decades of workarounds would be reimported alongside the processes they were designed to fix.</p>',
  '<p>The non-negotiable deadline combined with a complex legacy environment created competing pressures: thoroughness versus speed, and stakeholder familiarity with legacy workflows versus adoption of modern designs. Mapping 20 years of customisation to understand what was genuinely needed versus historical accident required significant analytical work.</p>',
  '<p>Served as Senior BPC responsible for process design, legacy customisation analysis, and go-live readiness. Led workshops to distinguish business requirements from implementation artefacts in the legacy system.</p>',
  '<p>Began with a structured legacy analysis phase categorising all customisations by business need, workaround, and obsolete. This produced a clean requirements baseline. Process designs were validated against current operational scenarios, not legacy documentation.</p>',
  '<p>Delivered on the hard deadline without service disruption and without replicating the legacy technical debt. The implementation provided a clean, modern ITSM foundation for an organisation that had not had one for two decades.</p>',
  '<p>Legacy replacement projects carry a hidden risk: the desire for familiarity can lead teams to replicate problems they do not recognise as problems. The legacy analysis phase — categorising customisations by their actual business justification — was the most valuable investment in the project.</p>'
),
(
  'Technology Services Partner — Full Platform Transformation (ITBM + CSM + ITSM + HAM)',
  'technology-services-partner-full-platform',
  'Technology Services Partner (Sanitised)',
  'Technology Services',
  'transformation',
  'published', 'sanitised', false,
  'Implement 75% of the ServiceNow platform in a single project — ITBM, CSM/Field Services, ITSM, and HAM — for an organisation that deliberately chose to run before it walked.',
  'BPC',
  '2020-09-01', '2021-03-31',
  ARRAY['IT Business Management','Customer Service Management','Field Service Management','IT Service Management','Hardware Asset Management'],
  ARRAY[]::text[],
  ARRAY['full-platform','PPM','CSM','FSM','HAM','transformation'],
  '<p>A technology services organisation made the deliberate decision to implement a large portion of the ServiceNow platform in a single project — bypassing the conventional crawl-walk-run approach. The ambition was to achieve full operational capability across ITBM, CSM, Field Service Management, ITSM, and HAM simultaneously.</p>',
  '<p>Broad-scope implementations create risk through interdependencies, resource contention, and stakeholder fatigue. The consultant''s role was to deliver the client''s ambition while protecting them from the predictable failure modes of over-broad scope. Identifying anticipated obstacles and communicating them proactively was as important as the technical delivery.</p>',
  '<p>Served as BPC across all workstreams, providing cross-domain design consistency and stakeholder alignment. Early identification of scope risks and communication of anticipated obstacles was an explicit part of the engagement model.</p>',
  '<p>Applied a dependency-mapping approach to sequence the implementation so foundational elements were established before dependent capabilities. Cross-domain process design sessions ensured consistency across module boundaries. Proactive risk communication kept the client informed before obstacles materialised.</p>',
  '<p>Successful delivery across all five platform areas. The Engagement Manager noted: "Tremendous work — this customer wanted to Run Run Run instead of Crawl Walk Run." The proactive obstacle communication approach was cited as an example of the delivery advantage that experience provides.</p>',
  '<p>The most valuable thing a consultant brings to an ambitious scope is honest, proactive obstacle communication. Clients who choose an aggressive approach need a partner who will tell them specifically what obstacles they will face and help them navigate — not one who executes the brief and escalates problems when they arrive.</p>'
),
(
  'Large Professional Services Firm — CSM Mobile Application & Operating Model Redesign',
  'professional-services-csm-mobile-app-redesign',
  'Large Professional Services Firm (Sanitised)',
  'Professional Services',
  'implementation',
  'published', 'sanitised', true,
  'Design and deployment of a custom mobile application for customer account management on ServiceNow CSM, distributed via Apple App Store and Google Play, alongside a redesign of ITSM and CSM operating models.',
  'Senior BPC, Lead Business & Process Architect, UX Design',
  '2022-06-01', '2023-03-31',
  ARRAY['Customer Service Management','IT Service Management'],
  ARRAY[]::text[],
  ARRAY['mobile-app','CSM','ITSM','app-store','operating-model','professional-services'],
  '<p>A large professional services firm needed to give its external clients direct access to engagement status, account team support, and industry experts through a branded mobile application, distributed via the Apple App Store and Google Play. Alongside the mobile application, the firm''s internal ITSM and CSM operating models needed to be reassessed and redesigned.</p>',
  '<p>Building a consumer-distributed mobile application on a ServiceNow CSM backend is extremely complex. The application needed to meet app store standards for performance, security, and user experience while operating within ServiceNow''s CSM data model.</p>',
  '<p>Served as Senior BPC and lead business and process architect, responsible for the end-to-end design of the mobile application experience, the CSM data model, and the integration between the consumer mobile layer and ServiceNow''s backend processes. Also led UX design.</p>',
  '<p>Treated the operating model redesign and application design as a single integrated workstream — processes, data model, and user experience were designed together. Used a consumer UX design approach (persona mapping, user journey design, prototype testing) for the mobile application.</p>',
  '<p>The mobile application launched successfully on both the Apple App Store and Google Play. The project resulted in a "successful and timely launch" of a mobile application giving end customers real-time access to engagement status and support.</p>',
  '<p>Consumer-facing applications on enterprise platforms require consumer-grade design methods. The persona and journey design work done before any ServiceNow configuration began was what made the mobile application genuinely useful — not just technically functional.</p>'
);
