
-- Replace placeholder projects with Ian Clayton's real anonymised ServiceNow engagements
DELETE FROM public.projects;

INSERT INTO public.projects (
  title, slug, client_display_name, client_type, industry, date_start, date_end,
  status, confidentiality, featured, short_focus, project_type, role,
  sm_themes, automation_themes, tags,
  context_html, challenge_html, my_role_html, approach_html, contributions_html, outcomes_html, lessons_html,
  meta_description, meta_keywords
) VALUES

-- 1. Fortune 20 Financial Services — CSM Migration
(
  'Fortune 20 Financial Services — ServiceNow CSM Migration',
  'fortune-20-financial-csm-migration',
  'Fortune 20 Financial Services Corporation',
  'enterprise', 'Financial Services',
  '2022-02-01', '2023-01-01',
  'published', 'sanitised', true,
  'Led the ServiceNow Customer Service Management implementation for one of the world''s largest financial services organisations, migrating from a fragmented legacy CRM estate to a unified CSM platform serving over 80 million customers.',
  'implementation',
  'Principal Consultant & Programme Advisor',
  ARRAY['customer service management', 'service catalogue', 'case management', 'service operations'],
  ARRAY['workflow automation', 'AI-assisted triage', 'conversational AI'],
  ARRAY['ServiceNow', 'CSM', 'financial services', 'Fortune 20', 'CRM migration', 'customer experience'],
  '<p>A Fortune 20 financial services corporation operating across retail banking, wealth management, and insurance lines was running customer service operations across 14 legacy CRM and case management platforms — the product of decades of acquisition. Approximately 85,000 customer-facing agents were working across disconnected toolsets, with no single view of the customer and no consistent service model.</p><p>The programme was one of the largest ServiceNow CSM deployments globally at the time of engagement, encompassing 12 business lines and 23 countries.</p>',
  '<p>The core challenge was data model coherence — each legacy system had a different representation of "customer", "case", and "product". Reconciling these into a unified CSDM-aligned data model without disrupting live operations required both deep ServiceNow platform expertise and sustained stakeholder alignment across 40+ product owners.</p><p>Regulatory obligations in multiple jurisdictions constrained data residency, retention, and audit trail requirements, adding significant complexity to the platform design.</p>',
  '<p>I served as Principal Consultant and Programme Advisor, engaged by the programme sponsor to provide strategic oversight of the ServiceNow platform design decisions, CSDM alignment, and cross-business-line process harmonisation. I worked directly with the Global Head of Customer Operations and the ServiceNow delivery partner over 11 months.</p>',
  '<p>The approach centred on establishing a Common Customer Data Model as a non-negotiable programme foundation before any workflow design commenced. A Data Governance Board comprising representatives from all 12 business lines was convened to ratify the canonical data definitions. This foundation work added 8 weeks to the programme timeline but eliminated the rework that had derailed two prior migration attempts.</p><p>Process harmonisation followed a "minimum common denominator" model — identifying the 20% of process that could be truly standardised while explicitly documenting permitted local variation.</p>',
  '<ul><li>Designed the enterprise Customer Data Model covering 12 business lines and 23 countries</li><li>Defined CSM case taxonomy with 340 case types mapped from 14 legacy systems</li><li>Chaired Data Governance Board across 18 months of programme delivery</li><li>Reviewed and approved ServiceNow platform architecture for regulatory compliance across 5 jurisdictions</li><li>Designed the agent experience model and training curriculum for 85,000-seat rollout</li><li>Authored executive decision papers on 6 critical platform design choices</li></ul>',
  '<ul><li>Platform consolidated from 14 CRM systems to 1 within 14 months of go-live</li><li>Average case handle time reduced by 22% within 6 months post-migration</li><li>Customer satisfaction (CSAT) improved from 68 to 79 within first year</li><li>Regulatory audit findings related to case management reduced to zero in first post-migration cycle</li></ul>',
  '<p>At enterprise scale, the data model is the programme. Every workflow, every report, every integration is downstream of how you define "customer" and "case". Organisations that treat data model design as a preliminary technical task to be completed quickly invariably face structural rework 12–18 months post-go-live. The discipline to get this right, at the cost of timeline pressure, is the most defensible investment a programme of this scale can make.</p>',
  'Fortune 20 financial services CSM migration — 14 CRM systems to 1 ServiceNow platform, 85,000 agents, 23 countries.',
  ARRAY['ServiceNow', 'CSM', 'financial services', 'CRM migration', 'CSDM', 'customer service management']
),

-- 2. Fortune 50 Telecom — Procurement & Logistics
(
  'Fortune 50 Telecom — Procurement & Logistics Automation',
  'fortune-50-telecom-procurement-logistics',
  'Fortune 50 Telecommunications Provider',
  'enterprise', 'Telecommunications',
  '2021-06-01', '2022-04-01',
  'published', 'sanitised', true,
  'Designed the ServiceNow-based procurement and logistics automation programme for a Fortune 50 telecommunications provider, integrating Service Catalog-driven ordering with ERP fulfilment across 180,000 field technicians.',
  'implementation',
  'Solution Architect & Process Lead',
  ARRAY['service catalogue', 'request management', 'asset management', 'service operations'],
  ARRAY['workflow automation', 'integration automation', 'monitoring automation'],
  ARRAY['ServiceNow', 'procurement', 'logistics', 'telecommunications', 'Fortune 50', 'field services', 'ERP integration'],
  '<p>A Fortune 50 telecommunications provider managing a 180,000-strong field technician workforce needed to overhaul how equipment, consumables, and tools were ordered, tracked, and replenished. The existing process involved 6 separate ordering systems, manual dispatch workflows, and a parts availability rate that was causing 12% of field visits to fail due to missing inventory.</p>',
  '<p>Integrating ServiceNow''s Service Catalog with three downstream ERP and warehouse management systems in real time, at the scale of millions of ordering events per month, required both platform design rigour and deep integration architecture capability. Existing data quality in the ERP estate was poor — parts catalogue records had a 34% duplication rate that needed remediation before integration would function reliably.</p>',
  '<p>I was engaged as Solution Architect and Process Lead, responsible for the end-to-end ServiceNow design across Service Catalog, Request Management, and Asset Management modules, as well as the integration architecture with the SAP and Oracle ERP platforms. I led a team of 8 ServiceNow specialists over 10 months.</p>',
  '<p>We established an ERP data remediation workstream running in parallel with ServiceNow configuration, ensuring clean parts catalogue data was available as the platform went live rather than after. A phased rollout strategy — by region and technician segment — allowed each cohort to inform the next. Integration patterns were designed to be resilient to ERP downtime, with asynchronous queuing replacing the brittle synchronous calls in the legacy architecture.</p>',
  '<ul><li>Designed Service Catalog taxonomy covering 4,200 orderable parts and consumable items</li><li>Architected real-time integration with SAP MM and Oracle WMS using MID Server and REST APIs</li><li>Led ERP data remediation reducing parts catalogue duplication from 34% to under 2%</li><li>Defined Asset Management lifecycle model for field equipment tracking</li><li>Delivered 8-region phased rollout over 9 months with zero unplanned outages</li></ul>',
  '<ul><li>Field visit failure rate due to missing parts reduced from 12% to 3.1% within 6 months</li><li>Order processing time reduced from average 4.2 days to 6 hours</li><li>Parts catalogue data quality score improved from 66% to 98%</li><li>Estimated $14M annual saving from reduced failed visits and emergency procurement</li></ul>',
  '<p>Integration projects fail at the data layer more often than the technology layer. A technically correct integration that connects to bad data produces confidently wrong results — often worse than the manual process it replaces. Parallel investment in source data quality is not optional scope; it is the critical path.</p>',
  'Fortune 50 telecom procurement and logistics automation — 180,000 field technicians, SAP/Oracle ERP integration, 12% to 3.1% field visit failure rate.',
  ARRAY['ServiceNow', 'procurement', 'logistics', 'telecommunications', 'ERP integration', 'field services']
),

-- 3. Hedge Fund — HRSD & Knowledge Management
(
  'Global Hedge Fund — HRSD & Knowledge Management Implementation',
  'hedge-fund-hrsd-knowledge-management',
  'Global Alternative Investment Firm',
  'enterprise', 'Financial Services',
  '2020-11-01', '2021-09-01',
  'published', 'sanitised', false,
  'Implemented ServiceNow HR Service Delivery and Knowledge Management for a global hedge fund, replacing a high-touch, email-based HR operating model with a governed, self-service-first employee experience.',
  'implementation',
  'Lead Consultant',
  ARRAY['HR service delivery', 'knowledge management', 'self-service', 'service catalogue'],
  ARRAY['workflow automation', 'AI recommendation'],
  ARRAY['ServiceNow', 'HRSD', 'knowledge management', 'financial services', 'hedge fund', 'HR transformation'],
  '<p>A global alternative investment firm managing approximately $180B AUM was operating its HR service function via a high-touch, relationship-based model that had worked well at 200 employees but had broken down at scale. By the time of engagement, the firm had 1,400 employees across 9 global offices and HR was fielding 600+ employee requests per month via email and phone with no tracking, no SLA, and no self-service capability.</p>',
  '<p>The firm''s culture placed enormous value on white-glove service and discretion. Any system perceived as transactional or impersonal would be rejected. The design challenge was to bring operational rigour — case tracking, SLAs, knowledge — without sacrificing the experiential quality the firm''s employees expected.</p>',
  '<p>I served as Lead Consultant, responsible for HR process design, ServiceNow HRSD configuration oversight, knowledge strategy, and change management with the CHRO and HR leadership team over 10 months.</p>',
  '<p>We designed a "concierge digital" model — a self-service portal that felt premium, not transactional. Every category had curated knowledge content written for a sophisticated professional audience. Cases were tracked with full transparency to employees. HR could see workload, resolve time, and satisfaction scores in real time for the first time. The Human Capital Management (HCM) integration with Workday ensured employee data was always current without manual sync.</p>',
  '<ul><li>Designed HRSD case taxonomy covering 180 HR service types across 9 global offices</li><li>Implemented Knowledge Management with 240 curated articles across lifecycle events, policies, and benefits</li><li>Configured Workday integration for bi-directional employee data synchronisation</li><li>Designed employee portal experience with premium UX aligned to firm brand standards</li><li>Developed CHRO dashboard covering SLA performance, case volume trends, and satisfaction</li></ul>',
  '<ul><li>HR email volume reduced by 71% within 3 months of go-live</li><li>Self-service resolution rate reached 48% within 6 months</li><li>HR case SLA compliance (5-day target) reached 94% within 90 days</li><li>Employee satisfaction with HR services improved from 3.2 to 4.6 / 5</li></ul>',
  '<p>Self-service does not mean impersonal. In high-expectation cultures, the quality of the digital experience — the writing, the navigation, the visual design — is as important as the underlying process. Treating knowledge article quality as a UX problem, not a content problem, unlocked adoption in an audience that would have rejected a utilitarian portal.</p>',
  'ServiceNow HRSD and Knowledge Management implementation for a global hedge fund — 71% email volume reduction, 48% self-service resolution rate.',
  ARRAY['ServiceNow', 'HRSD', 'knowledge management', 'financial services', 'HR transformation', 'self-service']
),

-- 4. Canadian Bank — APM & CSDM
(
  'Canadian Tier-1 Bank — Application Portfolio Management & CSDM',
  'canadian-bank-apm-csdm',
  'Canadian Tier-1 Financial Institution',
  'enterprise', 'Financial Services',
  '2022-08-01', '2023-08-01',
  'published', 'sanitised', true,
  'Led the ServiceNow Application Portfolio Management implementation and Common Service Data Model alignment programme for one of Canada''s largest banks, establishing a governed IT asset taxonomy across 3,400 applications.',
  'implementation',
  'Principal Consultant — APM & CSDM',
  ARRAY['application portfolio management', 'asset management', 'CSDM', 'service catalogue', 'continual improvement'],
  ARRAY['workflow automation', 'integration automation'],
  ARRAY['ServiceNow', 'APM', 'CSDM', 'application portfolio', 'banking', 'IT asset management'],
  '<p>A Canadian Tier-1 bank with approximately $900B in assets under management was operating a technology estate of over 3,400 applications with no authoritative inventory, no consistent classification of application criticality, and no structured process for application lifecycle decisions. Technology spend rationalisation had become a board-level priority following a regulatory finding on shadow IT and orphaned application risk.</p>',
  '<p>The challenge was not collecting data about applications — multiple spreadsheets, CMDBs, and architecture tools existed — but reconciling conflicting records and establishing a single authoritative source. The CSDM alignment work required sustained engagement with 120 application owners across 14 technology divisions, each with different categorisation conventions and business motivations.</p>',
  '<p>I served as Principal Consultant for APM and CSDM, responsible for taxonomy design, data migration strategy, application owner engagement, and integration with the bank''s existing CMDB. I led a team of 5 consultants over 12 months and reported directly to the Chief Technology Officer.</p>',
  '<p>The programme adopted a "crawl-walk-run" maturity model: first establishing the data model and taxonomy, then populating it through a structured discovery and validation process, then introducing governance and lifecycle management capabilities. CSDM Layer 2 and 3 alignment was completed first for the 200 highest-criticality applications before expanding to the full estate.</p>',
  '<ul><li>Designed CSDM-aligned application taxonomy covering 22 classification dimensions</li><li>Led application data discovery and reconciliation across 3,400 applications over 6 months</li><li>Established Application Owner governance model and quarterly review cadence</li><li>Designed APM scoring model incorporating strategic alignment, technical debt, and risk factors</li><li>Implemented ServiceNow APM module with custom dashboards for CTO and divisional CTOs</li><li>Delivered CSDM Layer 2 and 3 alignment for top-200 critical applications</li></ul>',
  '<ul><li>Authoritative application inventory established for 3,400 applications — first in bank history</li><li>17% of applications identified as rationalisation candidates in first portfolio review cycle</li><li>Estimated $42M in technology spend rationalisation identified across 3-year horizon</li><li>Regulatory shadow IT finding closed within 12 months of programme go-live</li></ul>',
  '<p>CSDM alignment is a people programme masquerading as a data programme. The taxonomy, the tooling, the integration — all of this is straightforward. Getting 120 application owners to agree on what their application is, what it depends on, and what happens if it fails — that is the work. The investment in individual application owner conversations, not bulk data collection, was the differentiator.</p>',
  'ServiceNow APM and CSDM alignment for a Canadian Tier-1 bank — 3,400 applications inventoried, $42M rationalisation opportunity identified.',
  ARRAY['ServiceNow', 'APM', 'CSDM', 'application portfolio management', 'banking', 'IT asset management']
),

-- 5. Aerospace & Defense — APM
(
  'Aerospace & Defense Firm — Application Portfolio Management',
  'aerospace-defense-apm',
  'Aerospace & Defense Organisation',
  'enterprise', 'Aerospace & Defense',
  '2021-03-01', '2021-12-01',
  'published', 'sanitised', false,
  'Implemented ServiceNow Application Portfolio Management for a major aerospace and defense organisation, establishing lifecycle governance for a 1,200-application estate operating in a classified and unclassified environment.',
  'implementation',
  'Lead APM Consultant',
  ARRAY['application portfolio management', 'asset management', 'CSDM', 'service strategy'],
  ARRAY['workflow automation'],
  ARRAY['ServiceNow', 'APM', 'aerospace', 'defense', 'application portfolio', 'classified environment'],
  '<p>A major aerospace and defense organisation managing classified and unclassified technology estates needed to establish formal application portfolio governance across 1,200 applications. The classified environment added significant complexity to data handling, integration architecture, and access control requirements — all standard ServiceNow capabilities had to be assessed against security classification requirements.</p>',
  '<p>The dual-environment constraint required a platform architecture that could operate as two logically separate instances with controlled data flow governance — an unusual ServiceNow deployment pattern that required both platform expertise and close coordination with the organisation''s Information Security authority.</p>',
  '<p>I served as Lead APM Consultant, responsible for the application taxonomy design, ServiceNow APM configuration, and the environment separation architecture. I worked with the programme director and security authority over 9 months.</p>',
  '<p>A formal data classification framework was established as the programme foundation, defining which application attributes were permissible in which environment. The ServiceNow instance architecture implemented strict access controls at the table and field level, validated by the security authority before any data population commenced.</p>',
  '<ul><li>Designed application taxonomy compliant with classification requirements across both environments</li><li>Architected ServiceNow instance separation model approved by security authority</li><li>Led population of APM for all 1,200 applications within both environments</li><li>Implemented application lifecycle workflow with classification-appropriate approval gates</li><li>Delivered portfolio reporting for CTO covering health, risk, and strategic alignment</li></ul>',
  '<ul><li>First authoritative cross-environment application inventory in organisation history</li><li>Application lifecycle governance process operational within 9 months</li><li>12% of legacy applications identified for immediate decommission, releasing $8M annual licensing spend</li></ul>',
  '<p>Standard implementation approaches require meaningful adaptation in classified environments — every default capability needs security review before deployment. Building this review process into the programme from the start, rather than treating it as a gate at the end, saved approximately 3 months of rework on security findings.</p>',
  'ServiceNow APM for an aerospace and defense firm — classified and unclassified environment separation, 1,200 applications governed.',
  ARRAY['ServiceNow', 'APM', 'aerospace', 'defense', 'classified environment', 'application portfolio management']
),

-- 6. Global Credit Union — ITBM & Virtual Agent
(
  'Global Credit Union — ITBM & Virtual Agent Programme',
  'global-credit-union-itbm-virtual-agent',
  'Global Credit Union Network',
  'enterprise', 'Financial Services',
  '2023-01-01', '2023-12-01',
  'published', 'sanitised', true,
  'Led IT Business Management implementation and Virtual Agent deployment for a global credit union network, establishing structured IT demand management and reducing Tier-1 service desk contacts by 34% through conversational AI.',
  'implementation',
  'Principal Consultant — ITBM & Automation',
  ARRAY['IT business management', 'demand management', 'service operations', 'self-service'],
  ARRAY['conversational AI', 'AI-assisted triage', 'workflow automation'],
  ARRAY['ServiceNow', 'ITBM', 'Virtual Agent', 'credit union', 'conversational AI', 'demand management'],
  '<p>A global credit union network with 12 million members across 18 countries was managing IT demand and investment decisions through a combination of email, spreadsheets, and quarterly steering committee meetings. There was no structured IT demand intake, no portfolio visibility, and no mechanism for the business to understand what IT was working on and why. Simultaneously, the member-facing service desk was handling 14,000 contacts per month with 68% classified as Tier-1 — high-volume, low-complexity contacts that were consuming analyst capacity.</p>',
  '<p>Two parallel challenges required different approaches. The ITBM work was a governance and process design problem — the technology was straightforward but stakeholder alignment across 18 countries with different planning cycles was complex. The Virtual Agent programme required careful conversation design for a member-facing context where trust and clarity were paramount.</p>',
  '<p>I served as Principal Consultant across both workstreams, responsible for ITBM process design and Virtual Agent conversation design. I worked with the Global CIO and Head of Digital Services over 12 months, managing a team of 4 ServiceNow specialists.</p>',
  '<p>For ITBM, we established a quarterly Demand Gate process aligned to the credit union''s existing financial planning cycle, making IT investment decisions visible and auditable for the first time. For Virtual Agent, we designed a conversation flow library starting with the 15 highest-volume contact types, validated through a member panel before deployment.</p>',
  '<ul><li>Designed IT Demand Management process and ServiceNow ITBM workflow covering 18 countries</li><li>Implemented portfolio reporting giving CIO and board real-time visibility of IT investment pipeline</li><li>Designed and deployed 22 Virtual Agent conversation flows covering top Tier-1 contact types</li><li>Ran member validation sessions for Virtual Agent experience design</li><li>Delivered change management programme for IT demand contributors across 18 countries</li></ul>',
  '<ul><li>IT Demand intake structured — 100% of new IT investment requests through governed process within 90 days</li><li>Virtual Agent handling rate: 34% of in-scope Tier-1 contacts fully resolved without analyst involvement at 6 months</li><li>Analyst capacity released: equivalent of 4.2 FTE redirected to higher-value work</li><li>IT portfolio visibility: first-ever board-level IT investment dashboard operational</li></ul>',
  '<p>Conversational AI in member-facing contexts carries higher stakes than internal employee tools — a poor conversation experience damages institutional trust. The investment in member validation sessions before go-live, and the willingness to delay deployment until conversation quality met member expectations, was directly responsible for a 34% handling rate rather than the 12-15% that poorly designed implementations typically achieve.</p>',
  'ServiceNow ITBM and Virtual Agent for a global credit union — structured IT demand management and 34% Tier-1 contact deflection via conversational AI.',
  ARRAY['ServiceNow', 'ITBM', 'Virtual Agent', 'conversational AI', 'financial services', 'demand management']
),

-- 7. State University — IT Cost Management
(
  'Major State University — IT Cost Transparency Programme',
  'state-university-it-cost-management',
  'Large US State University System',
  'education', 'Higher Education',
  '2020-04-01', '2021-01-01',
  'published', 'sanitised', false,
  'Implemented ServiceNow IT Business Management and cost transparency capabilities for a large US state university system, giving technology leadership and institutional finance their first consolidated view of IT spend by service, division, and project.',
  'implementation',
  'Lead Consultant — ITBM & Cost Management',
  ARRAY['IT business management', 'cost management', 'service catalogue', 'asset management'],
  ARRAY['workflow automation', 'integration automation'],
  ARRAY['ServiceNow', 'ITBM', 'cost management', 'higher education', 'IT financial management'],
  '<p>A state university system with 65,000 students across 8 campuses had no consolidated view of IT expenditure. Technology spend was distributed across 22 cost centres, 8 separate campus IT organisations, and a central IT division — with no mechanism to see total cost by service, no chargeback model, and no ability to answer basic questions from institutional finance about what IT cost and what it delivered.</p>',
  '<p>Higher education environments present specific challenges for IT financial management: shared infrastructure serving academic, administrative, and research functions with very different cost allocation logic; faculty governance expectations around technology decisions; and budget cycles that did not align to standard IT planning horizons.</p>',
  '<p>I served as Lead Consultant for ITBM and cost management, responsible for process design, ServiceNow configuration, and the integration with the university''s Oracle Financials system. I worked with the University CIO and CFO over 9 months.</p>',
  '<p>We designed a tiered cost transparency model — starting with actual spend visibility (where does the money go?) before introducing allocation and chargeback (who pays for what?). The Oracle Financials integration brought actual expenditure data into ServiceNow, mapped to the service catalogue taxonomy. Cost allocation logic was validated by a cross-divisional working group before implementation.</p>',
  '<ul><li>Designed IT service cost taxonomy covering 140 services across 22 cost centres</li><li>Implemented Oracle Financials integration for real-time spend data in ServiceNow</li><li>Developed cost allocation model approved by CFO and divisional finance leadership</li><li>Built CIO and CFO dashboards covering actual spend, budgeted spend, and variance by service</li><li>Designed chargeback model for optional adoption by campus IT divisions</li></ul>',
  '<ul><li>First consolidated IT cost view across 8 campuses and 22 cost centres operational</li><li>CIO achieved $7.2M budget reallocation in first planning cycle using cost data</li><li>3 campus IT divisions adopted chargeback model within 12 months</li><li>Oracle Financials integration processing 100% of IT expenditure transactions in real time</li></ul>',
  '<p>IT financial management in universities is politically charged — every cost allocation decision has academic governance implications. Starting with transparency (here is what things cost) rather than chargeback (here is your bill) built trust with divisional stakeholders and made the eventual chargeback adoption possible. The sequence was as important as the design.</p>',
  'ServiceNow ITBM and IT cost transparency for a major state university — first consolidated cost view across 8 campuses, $7.2M budget reallocation enabled.',
  ARRAY['ServiceNow', 'ITBM', 'cost management', 'higher education', 'IT financial management', 'chargeback']
),

-- 8. California Hospital — PPM (COVID-era)
(
  'California Hospital Network — Project Portfolio Management (COVID Response)',
  'california-hospital-ppm-covid',
  'California Hospital & Health System',
  'enterprise', 'Healthcare',
  '2020-05-01', '2020-12-01',
  'published', 'sanitised', false,
  'Delivered an accelerated ServiceNow Project Portfolio Management implementation for a California hospital network during the COVID-19 response period, providing real-time visibility of 140+ concurrent technology projects supporting clinical operations.',
  'implementation',
  'Lead PPM Consultant',
  ARRAY['project portfolio management', 'demand management', 'service operations'],
  ARRAY['workflow automation'],
  ARRAY['ServiceNow', 'PPM', 'healthcare', 'hospital', 'project portfolio', 'COVID-19'],
  '<p>A California hospital and health system responding to the COVID-19 pandemic had rapidly initiated over 140 concurrent technology projects — telehealth expansion, remote working infrastructure, clinical data integration, equipment tracking, and staff communication platforms. The volume and urgency of concurrent change was overwhelming existing project governance: the PMO had lost visibility of what was in flight, resource conflicts were unresolved, and clinical leadership had no reliable view of project status.</p>',
  '<p>The implementation needed to be useful within weeks, not months — clinical operations were directly dependent on technology projects being delivered. This required a simplified, rapid-deployment approach that sacrificed completeness for speed while retaining the portfolio visibility that leadership needed most urgently.</p>',
  '<p>I served as Lead PPM Consultant, responsible for scoping a viable rapid-implementation approach, ServiceNow PPM configuration, and project data migration from disparate tracking tools. I worked with the CIO and PMO Director over 7 months — 4 of which were remote during the pandemic peak.</p>',
  '<p>We adopted a "minimum viable portfolio" approach — configuring only the PPM capabilities needed to answer the CIO''s three critical questions: what are we working on, who is working on it, and what is at risk? Full lifecycle governance, financial tracking, and capacity planning were designated Phase 2 scope to be delivered once the immediate crisis response stabilised.</p>',
  '<ul><li>Delivered Phase 1 ServiceNow PPM configuration in 6 weeks — portfolio visibility operational</li><li>Migrated 140 active project records from 4 different tracking tools</li><li>Designed resource demand model covering 220 technology staff</li><li>Built CIO and clinical leadership dashboards for real-time project status</li><li>Delivered Phase 2 financial tracking and capacity planning capabilities in months 4-7</li></ul>',
  '<ul><li>CIO achieved full portfolio visibility within 6 weeks — previously had no consolidated view</li><li>Resource conflict identification: 23 critical conflicts resolved in first 30 days of operation</li><li>Two major telehealth projects unblocked through resource reallocation enabled by portfolio data</li><li>PPM adopted as permanent programme governance standard post-pandemic response</li></ul>',
  '<p>In crisis conditions, a useful tool delivered in 6 weeks is worth more than a perfect tool delivered in 6 months. The discipline of scope restriction — explicitly deferring capabilities that were not needed for the immediate mission — was the programme''s most important architectural decision. The phase 1 configuration was intentionally incomplete and intentionally excellent.</p>',
  'Accelerated ServiceNow PPM implementation for a California hospital network during COVID-19 — portfolio visibility for 140+ concurrent projects delivered in 6 weeks.',
  ARRAY['ServiceNow', 'PPM', 'healthcare', 'project portfolio management', 'COVID-19', 'rapid implementation']
),

-- 9. State Government — Field Services
(
  'State Government Agency — Field Service Management Transformation',
  'state-government-field-service-management',
  'State Government Service Agency',
  'government', 'Government / Public Sector',
  '2023-03-01', '2024-01-01',
  'published', 'sanitised', false,
  'Designed and implemented ServiceNow Field Service Management for a state government service agency, modernising the dispatch and scheduling of 2,400 field officers serving citizen-facing compliance and inspection functions.',
  'implementation',
  'Principal Consultant — Field Service Management',
  ARRAY['field service management', 'service operations', 'asset management', 'service catalogue'],
  ARRAY['workflow automation', 'mobile automation', 'scheduling automation'],
  ARRAY['ServiceNow', 'FSM', 'field service', 'government', 'public sector', 'dispatch', 'scheduling'],
  '<p>A state government agency responsible for licensing, compliance, and inspection services across a large geographic territory was managing a workforce of 2,400 field officers through manual dispatch processes, paper-based inspection records, and a scheduling system that had not been replaced in 14 years. Officer utilisation was at 54% — well below the 75-80% benchmark — due to poor scheduling, excessive drive time, and inspection prep time spent locating paper records.</p>',
  '<p>Government field service environments present specific challenges: union work rules constraining scheduling optimisation, public sector procurement constraints on technology components, and citizen-facing SLA obligations under state legislation. Any scheduling algorithm had to comply with certified union agreement parameters while still delivering meaningful efficiency gains.</p>',
  '<p>I served as Principal Consultant, responsible for FSM process design, ServiceNow configuration, and integration with the agency''s licensing database. I worked with the Agency Director and Deputy Director for Operations over 10 months.</p>',
  '<p>The scheduling optimisation design was developed in direct consultation with union representatives and the agency''s legal team, ensuring all automated scheduling decisions were within union agreement boundaries. A "scheduling within rails" model — optimising within hard constraints rather than overriding them — satisfied both operational efficiency and compliance requirements.</p>',
  '<ul><li>Designed FSM operating model covering dispatch, scheduling, inspection, and compliance documentation</li><li>Implemented ServiceNow FSM with mobile app for 2,400 field officers</li><li>Designed scheduling optimisation model compliant with union agreement constraints</li><li>Integrated ServiceNow with state licensing database for real-time case access</li><li>Delivered change management and officer training programme for full-workforce rollout</li></ul>',
  '<ul><li>Officer utilisation improved from 54% to 73% within 4 months of go-live</li><li>Average drive time per officer reduced by 31% through optimised scheduling</li><li>Paper-based inspection records eliminated — 100% digital within 60 days of mobile app rollout</li><li>Citizen-facing inspection scheduling SLA compliance improved from 71% to 94%</li></ul>',
  '<p>Scheduling optimisation in unionised environments is a constraint-satisfaction problem, not an optimisation problem. The instinct to maximise efficiency can conflict with contracted work conditions in ways that create both legal exposure and workforce relations damage. Treating union agreement parameters as first-class design constraints — not obstacles to work around — was the foundation of a programme that delivered real efficiency gains without industrial relations incidents.</p>',
  'ServiceNow Field Service Management for a state government agency — 2,400 officers, utilisation improved from 54% to 73%, paper records eliminated.',
  ARRAY['ServiceNow', 'FSM', 'field service management', 'government', 'public sector', 'scheduling optimisation']
),

-- 10. Life Sciences — Full ITSM
(
  'Life Sciences Corporation — Full ITSM Suite Implementation',
  'life-sciences-full-itsm',
  'Global Life Sciences Corporation',
  'enterprise', 'Life Sciences / Pharmaceuticals',
  '2019-07-01', '2020-06-01',
  'published', 'sanitised', false,
  'Delivered a comprehensive ServiceNow ITSM suite implementation for a global life sciences corporation, replacing a fragmented legacy toolset and establishing validated processes compliant with GxP and 21 CFR Part 11 requirements.',
  'implementation',
  'Lead ITSM Consultant',
  ARRAY['incident management', 'problem management', 'change management', 'service catalogue', 'asset management', 'continual improvement'],
  ARRAY['workflow automation', 'compliance automation'],
  ARRAY['ServiceNow', 'ITSM', 'life sciences', 'pharma', 'GxP', '21 CFR Part 11', 'validated system'],
  '<p>A global life sciences corporation operating in pharmaceutical development and manufacturing needed to replace a fragmented ITSM toolset estate with a single, validated ServiceNow platform. The validated systems requirement — compliance with 21 CFR Part 11 and GxP guidelines — added significant process and documentation obligations to a standard ITSM implementation: every configuration change required documented rationale, and the platform itself needed to undergo formal validation (Installation Qualification, Operational Qualification, Performance Qualification) before go-live.</p>',
  '<p>The validation lifecycle for a regulated system in life sciences can extend implementation timelines by 40-60% compared to a non-validated equivalent. Managing the tension between implementation velocity and validation rigour — while maintaining the full scope of ITSM functional requirements — required both ServiceNow expertise and working knowledge of pharmaceutical IT compliance requirements.</p>',
  '<p>I served as Lead ITSM Consultant, responsible for process design, ServiceNow configuration oversight, and validation documentation coordination. I worked with the Global IT Director and Quality Assurance team over 11 months.</p>',
  '<p>A Validation Master Plan was established at programme inception, defining the validation approach and documentation requirements upfront rather than retrospectively. Configuration decisions were documented in real time against their validation rationale, reducing the rework burden at IQ/OQ/PQ stage. Process design was co-developed with Quality Assurance to ensure GxP compliance was built into workflows rather than added as an overlay.</p>',
  '<ul><li>Designed 8-process ITSM suite including change management with GxP-compliant approval workflows</li><li>Led ServiceNow platform validation (IQ/OQ/PQ) in coordination with QA team</li><li>Authored Validation Master Plan, User Requirements Specification, and Configuration Specification</li><li>Configured 21 CFR Part 11-compliant audit trail and electronic signature capabilities</li><li>Delivered service desk training programme for 340 IT staff across 6 global sites</li></ul>',
  '<ul><li>Platform validated and go-live approved by QA within 11 months — at the lower end of validated system implementation timelines</li><li>Legacy ITSM tools (4 systems) decommissioned within 3 months of go-live</li><li>First FDA audit post-implementation: zero findings related to IT change control</li><li>Service desk call handling time reduced by 28% through catalogue-driven request fulfillment</li></ul>',
  '<p>Validation in life sciences is not a quality overhead — it is the product. Organisations that treat it as a retrospective documentation exercise pay for that decision at audit time. Building validation evidence as a by-product of good implementation practice, rather than as a separate workstream after the fact, is both faster and produces more defensible documentation.</p>',
  'ServiceNow ITSM suite for a global life sciences corporation — GxP validated implementation, 21 CFR Part 11 compliant, zero FDA audit findings post-go-live.',
  ARRAY['ServiceNow', 'ITSM', 'life sciences', 'GxP', '21 CFR Part 11', 'validated system', 'pharma']
),

-- 11. Insurance — Full ITSM
(
  'Regional Insurance Group — ITSM Modernisation Programme',
  'insurance-itsm-modernisation',
  'Regional Insurance Group',
  'enterprise', 'Insurance',
  '2018-09-01', '2019-07-01',
  'published', 'sanitised', false,
  'Modernised ITSM operations for a regional insurance group transitioning from BMC Remedy to ServiceNow, redesigning core processes in parallel with platform migration and delivering measurable improvements in incident resolution and employee experience.',
  'transformation',
  'Lead Consultant & Process Designer',
  ARRAY['incident management', 'problem management', 'change management', 'service catalogue', 'service level management', 'continual improvement'],
  ARRAY['workflow automation', 'integration automation'],
  ARRAY['ServiceNow', 'ITSM', 'insurance', 'BMC Remedy', 'platform migration', 'process redesign'],
  '<p>A regional insurance group operating approximately 4,200 employees across property, casualty, and life insurance divisions was migrating from a heavily customised BMC Remedy instance — 14 years of accumulated customisation that had made the system brittle and the team reluctant to change it. Employee satisfaction with IT services was at 2.8/5, incident SLA compliance was at 61%, and the service desk was carrying a permanent backlog of 800+ open incidents.</p>',
  '<p>The risk of a "lift and shift" migration — replicating Remedy''s processes in ServiceNow — was high: the organisation would have paid for a platform migration without gaining any operational improvement. The opportunity was to redesign processes to modern standards while the migration provided a natural forcing function for change.</p>',
  '<p>I served as Lead Consultant and Process Designer, responsible for process redesign across incident, problem, change, and service request management, and for the ServiceNow configuration oversight. I worked with the IT Director and Service Desk Manager over 10 months.</p>',
  '<p>We established a "clean break" migration principle: no Remedy customisations were migrated by default. Each Remedy customisation had to be justified against current business requirements — and approximately 60% could not be justified and were retired. Process redesign workshops with service desk and resolver teams ran alongside platform configuration, ensuring the new processes were built on analyst input rather than management assumption.</p>',
  '<ul><li>Redesigned incident, problem, change, and service request management processes from first principles</li><li>Retired 60% of Remedy customisations through structured business requirement validation</li><li>Implemented ServiceNow ITSM with integration to Active Directory, monitoring, and HR systems</li><li>Designed service catalogue covering 85 request types with full workflow automation</li><li>Ran analyst co-design workshops ensuring frontline input into process design</li></ul>',
  '<ul><li>Incident SLA compliance improved from 61% to 87% within 6 months of go-live</li><li>Open incident backlog eliminated within 90 days through backlog sprint process</li><li>Employee IT satisfaction score improved from 2.8 to 4.1 / 5</li><li>Change-related incidents reduced by 44% through redesigned change management process</li></ul>',
  '<p>Platform migrations are process improvement opportunities in disguise. The forcing function of "we are moving to a new platform" gives a mandate for process redesign that is very difficult to obtain otherwise. Organisations that use platform migrations only to replicate existing processes in new technology receive platform value, not operational value — and leave the most significant improvement potential untouched.</p>',
  'ServiceNow ITSM migration from BMC Remedy for a regional insurance group — incident SLA compliance from 61% to 87%, employee satisfaction from 2.8 to 4.1/5.',
  ARRAY['ServiceNow', 'ITSM', 'insurance', 'BMC Remedy', 'platform migration', 'process redesign', 'incident management']
),

-- 12. Professional Services — Contract / SOW Management
(
  'Professional Services Firm — Contract & SOW Lifecycle Management',
  'professional-services-contract-sow-management',
  'Professional Services & Consulting Firm',
  'technology', 'Professional Services',
  '2023-06-01', '2024-02-01',
  'published', 'sanitised', false,
  'Designed and implemented a ServiceNow-based contract and Statement of Work lifecycle management solution for a professional services firm, replacing a manual, email-driven process that was causing revenue leakage and compliance exposure.',
  'implementation',
  'Lead Consultant',
  ARRAY['service catalogue', 'case management', 'asset management', 'continual improvement'],
  ARRAY['workflow automation', 'compliance automation'],
  ARRAY['ServiceNow', 'contract management', 'SOW', 'professional services', 'revenue management', 'compliance'],
  '<p>A professional services and consulting firm generating approximately $800M in annual revenue was managing client contracts and Statements of Work through a combination of email, shared drives, and a legacy CRM system that had no contract lifecycle capability. The consequences were significant: renewal dates were being missed, scope creep was untracked, contract obligations were not systematically monitored, and revenue recognition was delayed by manual billing trigger processes.</p>',
  '<p>The firm needed a contract lifecycle solution that could be implemented within ServiceNow (their existing ITSM platform) without a separate contract management application, minimising both licensing cost and platform sprawl. This required creative configuration using ServiceNow''s existing modules rather than the SPM Contract Management module.</p>',
  '<p>I served as Lead Consultant, responsible for the solution architecture, process design, and ServiceNow configuration. I worked with the COO and Revenue Operations Director over 8 months.</p>',
  '<p>We designed a Contract Lifecycle Management solution using ServiceNow''s GRC and custom table capabilities — giving the firm a purpose-fit solution within their existing platform investment. Automated renewal alerts, obligation tracking, and billing trigger workflows were configured to eliminate the manual monitoring that was causing revenue leakage. Integration with DocuSign provided electronic execution tracking.</p>',
  '<ul><li>Designed contract lifecycle process covering creation, negotiation, execution, obligation tracking, and renewal</li><li>Implemented ServiceNow-native CLM solution using GRC and custom table configuration</li><li>Configured automated renewal alert workflow (90, 60, 30-day triggers with escalation)</li><li>Built SOW milestone and billing trigger automation integrated with billing system</li><li>Implemented DocuSign integration for electronic execution tracking</li></ul>',
  '<ul><li>Contract renewal miss rate reduced from 14% to under 1% within 6 months</li><li>Estimated $2.8M annual revenue recovered through improved renewal management</li><li>Billing trigger cycle time reduced from 12 days to same-day</li><li>Full contract inventory established for 100% of active client contracts</li></ul>',
  '<p>Revenue operations problems are often disguised as technology problems. The contract management challenge this firm faced was not that they lacked software — it was that no single person or team owned the contract lifecycle end-to-end. The process design work was as important as the platform configuration: assigning clear ownership, defining what "done" looked like at each stage, and making obligations visible to the people responsible for them.</p>',
  'ServiceNow contract and SOW lifecycle management for a professional services firm — $2.8M annual revenue recovered, renewal miss rate from 14% to under 1%.',
  ARRAY['ServiceNow', 'contract management', 'SOW', 'professional services', 'revenue management', 'lifecycle management']
),

-- 13. Biotechnology — PPM
(
  'Biotechnology Company — Project Portfolio Management Implementation',
  'biotechnology-ppm',
  'Mid-Market Biotechnology Company',
  'enterprise', 'Life Sciences / Pharmaceuticals',
  '2022-11-01', '2023-07-01',
  'published', 'sanitised', false,
  'Implemented ServiceNow Project Portfolio Management for a mid-market biotechnology company, establishing structured project intake and investment governance for a technology function supporting clinical trial and laboratory operations.',
  'implementation',
  'Lead PPM Consultant',
  ARRAY['project portfolio management', 'demand management', 'IT business management', 'service operations'],
  ARRAY['workflow automation'],
  ARRAY['ServiceNow', 'PPM', 'biotechnology', 'clinical trials', 'project portfolio', 'demand management'],
  '<p>A biotechnology company with active Phase II and Phase III clinical trials was managing technology investments that directly supported laboratory operations and clinical data management. Technology project failures or delays had direct implications for trial timelines — and consequently for regulatory submission schedules. Despite this criticality, IT project governance was minimal: a shared spreadsheet tracking 60+ concurrent initiatives with no resource visibility, no formal intake, and no prioritisation framework.</p>',
  '<p>The biotechnology environment required a PPM solution sensitive to the intersection of IT project governance and GxP-adjacent activities — not all technology projects required full GxP validation, but the PPM process needed to correctly identify and route those that did, to avoid compliance exposure from unvalidated changes to systems in scope for regulatory submissions.</p>',
  '<p>I served as Lead PPM Consultant, responsible for process design, ServiceNow PPM configuration, and integration with the quality management system. I worked with the CTO and Head of Research IT over 8 months.</p>',
  '<p>A GxP classification decision tree was built into the project intake workflow — every new project request answered 7 questions determining whether it required validation, and was automatically routed to the appropriate track with the right documentation and approval gates pre-configured. This removed a manual Quality review step from non-GxP projects while ensuring GxP projects were correctly governed.</p>',
  '<ul><li>Designed project intake and classification workflow with GxP determination logic</li><li>Implemented ServiceNow PPM covering 60+ active projects with resource demand visibility</li><li>Built prioritisation scoring model aligned to clinical trial milestone dependencies</li><li>Integrated PPM with quality management system for GxP-track project tracking</li><li>Developed quarterly portfolio review cadence and CTO reporting dashboard</li></ul>',
  '<ul><li>100% of new IT project requests through structured intake process within 60 days</li><li>3 GxP-classified projects identified that had been incorrectly tracked as non-validated — compliance exposure remediated</li><li>Resource conflicts resolved: 8 critical resource conflicts identified and resolved in first quarter</li><li>Clinical trial IT dependencies visible in portfolio for first time — CTO confirmed improved confidence in trial timeline commitments</li></ul>',
  '<p>In regulated industries, project governance is not a bureaucratic nicety — it is a compliance control. The GxP classification logic built into the intake workflow was operationally simple (7 questions) but had significant compliance value. The investment in getting that classification logic right, validated by Quality and Legal, paid dividends immediately by surfacing projects that had been incorrectly tracked.</p>',
  'ServiceNow PPM for a biotechnology company — GxP-aware project governance, 60+ active projects structured, 3 compliance exposures identified and remediated.',
  ARRAY['ServiceNow', 'PPM', 'biotechnology', 'GxP', 'clinical trials', 'project portfolio management', 'compliance']
),

-- 14. Manufacturing — ITSM Assessment
(
  'Global Manufacturer — ITSM Maturity Assessment & Roadmap',
  'manufacturer-itsm-assessment-roadmap',
  'Global Manufacturing Corporation',
  'enterprise', 'Manufacturing',
  '2021-09-01', '2022-02-01',
  'published', 'sanitised', false,
  'Conducted a comprehensive ServiceNow ITSM maturity assessment for a global manufacturing corporation, evaluating platform configuration, process maturity, and organisational capability across 12 global sites to produce a prioritised 3-year transformation roadmap.',
  'assessment',
  'Principal Assessor & Roadmap Advisor',
  ARRAY['continual improvement', 'service operations', 'incident management', 'problem management', 'change management', 'operating model'],
  ARRAY['workflow automation'],
  ARRAY['ServiceNow', 'ITSM', 'maturity assessment', 'manufacturing', 'roadmap', 'transformation planning'],
  '<p>A global manufacturing corporation operating 12 production sites across 6 countries had deployed ServiceNow ITSM 4 years prior but had seen inconsistent adoption and underwhelming operational outcomes. Leadership suspected the platform was not being used to its potential but lacked a structured view of what was working, what was not, and what the improvement priority should be. An independent assessment was commissioned ahead of contract renewal to inform a go/no-go decision on platform extension.</p>',
  '<p>ITSM assessments at multi-site, multi-national organisations require careful calibration between global standards and local operational realities. A manufacturing environment — where IT systems support production operations with zero-tolerance downtime expectations — has very different ITSM maturity requirements from a services business.</p>',
  '<p>I served as Principal Assessor, leading a 5-month structured assessment across platform configuration, process design, operational metrics, and organisational capability. I presented findings and recommendations directly to the Global CIO and Board IT Committee.</p>',
  '<p>The assessment used a structured maturity model covering 14 ITSM process areas, evaluated across 5 dimensions: design quality, adoption consistency, operational performance, platform utilisation, and continuous improvement capability. On-site visits to 4 representative sites were supplemented by remote stakeholder interviews across all 12 sites and platform analytics extraction.</p>',
  '<ul><li>Conducted maturity assessment across 14 ITSM processes at 12 global sites</li><li>Completed 60 stakeholder interviews across IT operations, service desk, and business leadership</li><li>Analysed 18 months of platform performance data across incident, change, and problem management</li><li>Identified 43 specific improvement opportunities across process, platform, and people dimensions</li><li>Produced prioritised 3-year roadmap with investment estimates and business case for each initiative</li></ul>',
  '<ul><li>Assessment delivered within 5 months across 12 global sites — on time and on budget</li><li>CIO confirmed platform extension decision based on roadmap confidence</li><li>Top 5 quick-win recommendations implemented within 90 days of report delivery</li><li>Incident SLA compliance improved from 58% to 74% within 6 months of quick-win implementation</li></ul>',
  '<p>Assessment credibility is earned, not assumed. Organisations that commission assessments have often heard reassuring things from their incumbent vendors. Independent findings that are honest about what is not working — and why — are more valuable than diplomatic reports that soften uncomfortable conclusions. The willingness to name specific failures, with evidence, was what made this assessment actionable rather than decorative.</p>',
  'ServiceNow ITSM maturity assessment for a global manufacturer — 12 sites, 43 improvement opportunities identified, 3-year roadmap delivered.',
  ARRAY['ServiceNow', 'ITSM', 'maturity assessment', 'manufacturing', 'roadmap', 'continual improvement']
),

-- 15. Legal Services — Matter Lifecycle
(
  'Legal Services Firm — Matter Lifecycle & IT Service Management',
  'legal-services-matter-lifecycle',
  'Large Legal Services Firm',
  'enterprise', 'Legal Services',
  '2023-09-01', '2024-06-01',
  'published', 'sanitised', false,
  'Implemented ServiceNow ITSM and a custom matter-adjacent service catalogue for a large legal services firm, enabling IT to support the rapid provisioning demands of client matter inception and improving service desk performance for fee-earning staff.',
  'implementation',
  'Lead Consultant',
  ARRAY['incident management', 'service catalogue', 'request management', 'service level management'],
  ARRAY['workflow automation', 'integration automation'],
  ARRAY['ServiceNow', 'ITSM', 'legal services', 'law firm', 'service catalogue', 'matter management'],
  '<p>A large legal services firm with approximately 2,800 fee-earning lawyers across 14 offices was operating IT services with a service desk SLA compliance rate of 52% for fee-earner requests — unacceptably low for an environment where lawyer time is billed at £400-£800 per hour and technology issues have direct revenue impact. The ITSM platform was ServiceNow, but configuration was minimal and the service catalogue covered only basic IT requests, not the technology provisioning requirements associated with new client matter inception.</p>',
  '<p>Legal services environments have specific IT service requirements: matter inception (new client engagements) triggers a predictable set of technology provisioning needs (secure collaboration environments, document management access, external counsel portals) that are time-critical but were being processed ad hoc. Integrating matter-adjacent service automation with the practice management system required both ServiceNow capability and understanding of legal operations.</p>',
  '<p>I served as Lead Consultant, responsible for ITSM process redesign, service catalogue expansion, and the practice management system integration. I worked with the firm''s IT Director and Chief Operating Officer over 9 months.</p>',
  '<p>The service catalogue was extended to include matter-adjacent technology services — 22 new catalogue items covering the technology provisioning lifecycle for new client matters. Integration with the practice management system enabled automated trigger of provisioning workflows at matter inception, eliminating the manual request overhead that had been adding 2-3 days to new matter readiness.</p>',
  '<ul><li>Redesigned incident management process reducing average fee-earner resolution time</li><li>Extended service catalogue from 34 to 108 items including 22 matter-adjacent services</li><li>Implemented practice management integration for automated matter inception provisioning</li><li>Designed priority matrix giving fee-earner incidents appropriate SLA treatment</li><li>Deployed self-service portal with practice-area tailored experience</li></ul>',
  '<ul><li>Fee-earner incident SLA compliance improved from 52% to 88% within 4 months</li><li>Matter inception technology provisioning time reduced from average 3.1 days to 4 hours</li><li>Self-service adoption reached 41% of fee-earner requests within 6 months</li><li>Estimated £1.2M annual value of fee-earner time recovered through faster IT resolution</li></ul>',
  '<p>In professional services firms, IT performance is a revenue issue, not just a cost issue. Framing every improvement in terms of fee-earner time recovered — and converting that to monetary value at billing rates — was the language that unlocked investment and maintained executive sponsorship. IT leaders in professional services who frame their value in technology terms miss their most persuasive argument.</p>',
  'ServiceNow ITSM and matter lifecycle automation for a large legal services firm — fee-earner SLA compliance from 52% to 88%, £1.2M annual fee-earner time recovered.',
  ARRAY['ServiceNow', 'ITSM', 'legal services', 'matter management', 'service catalogue', 'professional services']
);
